### ISSUE TITLE
sample genomes at by varying degrees of diversity

### ISSUE THREAD

**Issue by gwarmstrong** [gwarmstrong/taxa-assign-benchmarking#24]
From @wasade:
> You could use clade width, or the maximum tip-tip distance spanned by a clade. ... The slightly tricky bit is to make sure you don’t gather nested clades (i.e., the tips represented by the selected clades should be mutually exclusive). 

> One take on this is expressing the complexity of the database by a proxy parameter, such as the minimum clade width to sample a genome from (where a small width equivalent to strain level and a large width is equivalent to phylum level).

**Comment by gwarmstrong** [comment]
It seems like this sort of selection makes the most sense if the taxonomy and phylogeny are coming from GTDB, since it has a model where they are more unified in terms of evolutionary divergence than perhaps other methods.

**Comment by gwarmstrong** [comment]
Figure 2 from GTDB paper is also helpful for interpreting this issue.

**Comment by wasade** [comment]
It also makes sense independent of taxonomy which is subjective. I
recommend chatting with Qiyun about WOL

**Comment by qiyunzhu** [comment]
@wasade we chatted yesterday, addressing GTDB and methods for subsampling.

@gwarmstrong for your further information, WoL has curated taxonomy following both NCBI and GTDB, either one is fully compatible with the phylogeny, and allows cross-comparison between the two systems.

https://biocore.github.io/wol/empress
https://biocore.github.io/wol/data/taxonomy/

@gwarmstrong The GTDB paper also introduced a metric "RED", which I used for subsampling genomes based on evolutionary distances in the WoL paper.

**Comment by gwarmstrong** [comment]
@qiyunzhu Thanks for more information!

> @gwarmstrong The GTDB paper also introduced a metric "RED", which I used for subsampling genomes based on evolutionary distances in the WoL paper.

I was just reading about this metric. @qiyunzhu Can you provide me with more information about how you used this for subsampling in WoL?

**Comment by qiyunzhu** [comment]
@gwarmstrong Here is my implementation:
https://github.com/biocore/wol/blob/master/code/notebooks/subsample.ipynb

Also see here:
https://github.com/biocore/wol/blob/master/code/utils/tree.py#L1395

**Comment by gwarmstrong** [comment]
@qiyunzhu Thank you!!

**Comment by gwarmstrong** [comment]
Plan after reading and discussing with @qiyunzhu :

From WoL:
1. Limit overall diversity by taking clades with nodes chosen by cutting the tree at any node that does not have a red score over a certain threshold, `t`.
2. For a clade in step 1, Create `n` classes as the nodes within the clade that minimize the sum of RED scores among `n` non-overlapping  sub-clades.
3. Sample genomes from each of the classes/sub-clades (sampling criteria TBD)

**Comment by gwarmstrong** [comment]
Closed by #35
